name: flippo
description: A new Flutter project.

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.8.1
  shimmer: ^1.1.1

  #For handling authentication via firebase

  firebase_auth: ^0.16.0

  #For handling google sign in

  google_sign_in: ^4.4.4

  #for fab animation and interaction
  flare_flutter: ^2.0.3

  #icons
  cupertino_icons: ^0.1.3

  #fonts
  google_fonts: ^1.1.0

  #for stories dashes
  dashed_circle: ^0.0.1

  # For making request to firestore database
  cloud_firestore: ^0.13.5

  #permissions handling
  permission_handler: 3.0.0

  # image_picker
  image_picker: 0.6.6+1

  #provider state management
  provider: ^4.0.3

  #firebase storage for storing images and stuffs
  firebase_storage: ^3.1.5

  #for using paths in apps
  path_provider: ^1.6.8

  #for caching image for great user experience
  cached_network_image: ^2.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - fab-button.flr
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
